FROM centos
LABEL description="Baseline CentOS docker image" version="0.01" Vendor="FlexStudios" authors="Kwok Yao Chim <yaochim8@gmail.com>"
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
