FROM centos
MAINTAINER Kwok Yao Chim yaochim8@gmail.com
LABEL description="Baseline CentOS docker image"
LABEL version="1.0"
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
